package com.dsa.ds3recursive;

import java.util.ArrayList;

/*
* You are given a keypad (as shown in the diagram) and an array arr[ ] containing digits,
* your task is to list all possible words in any order which can be generated by
*  pressing numbers in arr[] sequentially.

Note: Number 0 and 1 do not map to any letters.
You can return the words in any order, the driver code will print them in sorted order.
* Examples :

Input: arr[] = [2, 3]
Output: [ad, ae, af, bd, be, bf, cd, ce, cf]
Explanation: When we press 2 and 3 total 3 x 3 = 9 possible words formed.
Input: arr[] = [2]
Output: [a, b, c]
Explanation: When we press 2 total 3 possible words formed.
* */
public class _16PossibleWordsFromPhoneDigits {
    public static String[] keyboard =  {
            "", "", "abc", "def",
            "ghi", "jkl", "mno",
            "pqrs", "tuv", "wxyz"
    };
    public static void main(String[] args) {
        ArrayList<String> res = new ArrayList<>();
        int[] input={8,8,0};
        solve(input,0,"",res);
        System.out.println(res);
    }

    public static void solve(int[] arr, int index, String cur, ArrayList<String> res){
        if (index==arr.length){
            res.add(cur);
            return;
        }


        String letter = keyboard[arr[index]];

        if (letter.isEmpty()) {
            solve(arr, index + 1, cur, res);
            return;
        }
        for (int i=0;i<letter.length();i++){
            solve(arr,index+1,cur+letter.charAt(i),res);
        }
    }
}
